### ISSUE TITLE
A potential for harm to the accessibility and disability-equalization of social media across the world

### ISSUE THREAD

**Issue by hkolbeck** [mozilla/checkvite#1]
Hi there,

I've seen the announcement of this tool propagating excitedly between social media platforms and forums, with folks reacting negatively largely being dismissed. Unnoticed or ignored is that those raising alarms are largely folks who themselves rely on alt text or have been active advocates in this area.

While the text of the announcement tweet I saw suggests that the target is screen reader users the attached graphic hints at the possibility of the tool being available to users creating alt text for images they are adding to the web. The linked article makes it explicit that giving people writing alt text for images easy access to this AI is a future goal. That goal is prominently the source of almost every celebration I've seen for this across the web. The two groups of people wanting AI descriptions might seem next to interchangable, but ongoing patterns in usage of AI technology in alt text generation show that the effects are very different in ways I hope you will work to understand before moving forward.

A short resume to speak to my experience on this: I created the Twitter bot [@AltTxtReminder](https://github.com/alt-text-org/AltTxtReminder) in 2021 (banned after EM due to new restrictions on API usage) and have been actively involved in tools around social media alt text since. I first added AI image description to an existing Twitter bot in 2022: [code for the "describe" command](https://github.com/alt-text-org/AltTextCrew/blob/main/src/describe.js) and have been engaged since with the changes in that tech as well as with the people who rely on alt text. I founded and just passed off to [Scribely](https://www.scribely.com/) the [Alt-Text.org](http://alt-text.org) project, which is very related to the issues here. I would like to offer access to my experience via free advice or consultation on this.

It's a complex issue, and I do see possible paths to responsible offering of AI image description tools to those writing alt text, but the controls must be careful and UI/UX must be somewhat complex to be responsibly used. I am happy to go into details, but for reasons of my own disability written complex communication is difficult and I would prefer video chat if possible. I had a very recent major surgery but am able to advise and my schedule is completely open.

If there are better folks to speak to at Mozilla about this, please put us in touch.

Thank you,
Hannah
[hannah@alt-text.org](mailto:hannah@alt-text.org)

**Comment by tarekziade** [comment]
I will reach out by email. Thanks so much for offering your help and expertise

**Comment by hkolbeck** [comment]
I appreciate your email and still hope to provide said information, but now see that my statement above that Mozilla was publicly planning this availability was a misunderstanding. Based on this, while I see the above as useful in places this repo is not included there at this time and so am closing this, apologies.
